SHOW TABLES IN SCHEMA ANALYTICS.RAW

LIST @ANALYTICS.RAW.S3_STAGE;

SELECT COUNT(*) FROM ANALYTICS.RAW.CLIENTES;   -- esperado: 7
SELECT COUNT(*) FROM ANALYTICS.RAW.VENDAS;     -- esperado: 9

SELECT * FROM ANALYTICS.RAW.CLIENTES;
SELECT * FROM ANALYTICS.RAW.VENDAS;

SELECT * FROM ANALYTICS.ANALYTICS_ANALYTICS.VENDAS_POR_CLIENTE;